### ISSUE TITLE
Inclusion of data in `uiucdata` R data package

### ISSUE THREAD

**Issue by coatless** [wadefagen/Teachers-Ranked-As-Excellent-UIUC#1]
@wadefagen Would it be okay if I included this data in [`uiucdata`](https://github.com/coatless/uiucdata) R data package?

**Comment by wadefagen** [comment]
Certainly! :)

**Comment by coatless** [comment]
Excellent. Thanks! FYI, let me know if you are interested in wi-fi data. c.f. http://stat385.thecoatlessprofessor.com/homework-05-direct-effect/#15-points-exercise-7-can-you-hear-me-now

**Comment by coatless** [comment]
Thanks again @wadefagen. It's now available in _R_:

https://github.com/coatless/uiucdata/commit/a8c102cb2cb2647d862e98d599e28be4c177fe07
